## data path 
data_dir: "./data/"
saved_model_dir: "./checkpoints/acdc/"

## dataset parameters
num_classes: 4
input_size: 96
input_channels: 1

## model parameters 
feature_size: 48

## training parameters
learning_rate: 0.0001
weight_decay: 0.00001
max_iterations: 30000
eval_num: 500
use_checkpoint: true

## dataloader parameters
num_samples: 4
train_cache_num: 100
cache_rate: 1.0
train_num_workers: 8
val_num_workers: 1
batch_size: 1
val_cache_num: 20

################################ Augmentation
## Spacingd
pixdim: [1.0, 1.0, 1.0]

## rands
prob_RandFlipd: 0.10
prob_RandRote: 0.10
prob_ShiftInten: 0.50
offset_ShiftInten: 0.50

## test 
save_dir: pics/